name: First Workflow
on: 
   push:
     branches:
       - main 
       - develop
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome the first workflow!"
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
